libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_trylock,lock,def{264},use{266},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_lock,lock,def{258},use{260},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_init,pshared,def{246},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_init,lock,def{246},use{248},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_unlock,mutex,def{224},use{},dvars{},pointers{doms,driverState,privconn,lockd,lockspace,ipl,client,eventLoop,priv,ifname,dom,sasl,uml_driver,ctx,srv,nwfilter,sess,m,obj,dev,mgr,vm,conn,req,state,c,nwfilters,driver,storageState,privinterface,ctl},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_destroy,lock,def{252},use{254},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_trylock,mutex,def{218},use{220},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_lock,mutex,def{210},use{},dvars{},pointers{opaque,ka,dev,mgr,cache,sock,dom,obj,client,privconn,secret,vm,test,pools,priv,fuse,conn,driver,m},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_destroy,mutex,def{195},use{},dvars{},pointers{lockd,cfg,pools,cache,fuse,req,obj,lockspace,ifkey,pool,m},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutexattr_init,attr,def{183},use{},dvars{},pointers{attr},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_exit,value,def{162},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_join,pvalue,def{169},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_join,thread,def{169},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_create,arg,def{155},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_create,,def{155},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_create,start_routine,def{155},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_create,attr,def{154},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_create,thread,def{153},use{},dvars{},pointers{t},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_wait,mutex,def{145},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_wait,cond,def{144},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_init,attr,def{203},use{},dvars{},pointers{attr},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutex_init,mutex,def{202},use{},dvars{},pointers{m},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutexattr_destroy,attr,def{177},use{},dvars{},pointers{attr},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_signal,cond,def{137},use{},dvars{},pointers{tmp,call,driver,mon,con,c},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutexattr_settype,attr_type,def{189},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_mutexattr_settype,attr,def{189},use{},dvars{},pointers{,attr},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_init,attr,def{130},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_init,cond,def{129},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_spin_unlock,lock,def{270},use{272},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/gnulib/lib/pthread.in.h,pthread_cond_destroy,cond,def{122},use{},dvars{},pointers{},cfuncs{}
