libvirt-1.1.0/tests/testutils.h,GLOBAL,func,def{65},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,argv,def{64},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,length,def{56},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,actual,def{52,55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,expect,def{51,54},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,argc,def{63},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,pattern,def{47},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,stream,def{50,53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,maxlen,def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,buf,def{44,45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,data,def{43},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,argv[],def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,file,def{44},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,title,def{40},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,ret,def{38},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,items,def{35},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,bodydata,def{42},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,,def{38,42,58,59,61,65,68,73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,string,def{48},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,msg,def{38},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,nitems,def{36},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,nloops,def{41},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/testutils.h,GLOBAL,name,def{38},use{},dvars{},pointers{},cfuncs{}
