libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByUUID,exp,def{211},use{212},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByUUID,argv,def{210},use{212},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByUUID,ATTRIBUTE_UNUSED,def{209},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByID,exp,def{205},use{206},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByID,argv,def{204},use{206},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByID,ATTRIBUTE_UNUSED,def{203},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByUUID,exp,def{199},use{200},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByUUID,argv,def{198},use{200},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByUUID,ATTRIBUTE_UNUSED,def{197},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByID,exp,def{169},use{170},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByID,argv,def{168},use{170},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByID,ATTRIBUTE_UNUSED,def{167},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByUUID,exp,def{187},use{188},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByUUID,argv,def{186},use{188},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByUUID,ATTRIBUTE_UNUSED,def{185},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByName,exp,def{163},use{164},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByName,argv,def{162},use{164},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByName,ATTRIBUTE_UNUSED,def{161},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareEcho,info,def{227},use{228},dvars{},pointers{data},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareEcho,data,def{226},use{227},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByName,exp,def{181},use{182},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByName,argv,def{180},use{182},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomidByName,ATTRIBUTE_UNUSED,def{179},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByUUID,exp,def{157},use{158},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByUUID,argv,def{156},use{158},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByUUID,ATTRIBUTE_UNUSED,def{155},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByID,exp,def{151},use{152},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByID,argv,def{150},use{152},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDominfoByID,ATTRIBUTE_UNUSED,def{149},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoCustom,exp,def{136},use{146},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoCustom,argv,def{131},use{146},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoCustom,ATTRIBUTE_UNUSED,def{130},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,mymain,ret,def{235,243,247,251,255,259,263,267,271,275,279,283,287,291,295,299,303},use{243,247,251,255,259,263,267,271,275,279,283,287,291,295,299,303,398},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,mymain,,def{233},use{237,238,242,246,250,254,258,262,266,270,274,278,282,286,290,294,298,302,330,334,346,348,351,352,353,398},dvars{ret},pointers{},cfuncs{va_end{1},virVasprintf{3},va_start{1},virtTestRun{4},virtTestRun{3},virAsprintf{3},virAsprintf{1}}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoDefault,exp,def{117},use{127},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoDefault,argv,def{116},use{127},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareNodeinfoDefault,ATTRIBUTE_UNUSED,def{115},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListCustom,exp,def{106},use{112},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListCustom,argv,def{105},use{112},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListCustom,ATTRIBUTE_UNUSED,def{104},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByName,exp,def{175},use{176},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByName,argv,def{174},use{176},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomuuidByName,ATTRIBUTE_UNUSED,def{173},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListDefault,exp,def{96},use{101},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListDefault,argv,def{95},use{101},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareListDefault,ATTRIBUTE_UNUSED,def{94},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByName,exp,def{217},use{218},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByName,argv,def{216},use{218},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomstateByName,ATTRIBUTE_UNUSED,def{215},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testFilterLine,start,def{44,51},use{50,51,53},dvars{},pointers{},cfuncs{memmove{1}}
libvirt-1.1.0/tests/virshtest.c,testFilterLine,toRemove,def{43},use{47},dvars{EXIT_SUCCESSEXIT_FAILUREEXIT_AM_SKIPstart},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testFilterLine,EXIT_SUCCESSEXIT_FAILUREEXIT_AM_SKIPstart,def{47},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testFilterLine,end,def{45,50},use{53},dvars{},pointers{start},cfuncs{strlen{3},memmove{2}}
libvirt-1.1.0/tests/virshtest.c,testFilterLine,buffer,def{42},use{47},dvars{EXIT_SUCCESSEXIT_FAILUREEXIT_AM_SKIPstart},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareOutputLit,argv[],def{60},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareOutputLit,filter,def{60},use{68},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareOutputLit,actualData,def{63},use{65,68,71,72,79,356,359,360,385},dvars{},pointers{},cfuncs{VIR_FREE{1},(int) {3},strlen{1},virtTestDifference{3}}
libvirt-1.1.0/tests/virshtest.c,testCompareOutputLit,result,def{62,76},use{76,81},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareOutputLit,expectData,def{59},use{71,72},dvars{},pointers{},cfuncs{virtTestDifference{2}}
libvirt-1.1.0/tests/virshtest.c,main,,def{15},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByID,exp,def{193},use{194},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByID,argv,def{192},use{194},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/tests/virshtest.c,testCompareDomnameByID,ATTRIBUTE_UNUSED,def{191},use{},dvars{},pointers{},cfuncs{}
