libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,flags,def{151,156,160},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,dst,def{147},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,src,def{146},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,mode,def{143},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,policy,def{165},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,buf,def{154,158},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,ctxt,def{142},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,node,def{141},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,name,def{164},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,cpu,def{138,163},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/cpu_conf.h,GLOBAL,def,def{130,150,155,159},use{},dvars{},pointers{},cfuncs{}
