libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageRegister,,def{611},use{613},dvars{},pointers{},cfuncs{virRegisterStorageDriver{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolIsPersistent,ATTRIBUTE_UNUSED,def{568},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolIsActive,ATTRIBUTE_UNUSED,def{559},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetPath,backend,def{545},use{553},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetPath,priv,def{544},use{549},dvars{},pointers{volume},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetPath,volume,def{542},use{544,545,547,553},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetInfo,backend,def{511},use{519},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetInfo,priv,def{510},use{515},dvars{},pointers{volume},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetInfo,info,def{508},use{519},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetInfo,volume,def{508},use{510,511,513,519},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolDelete,backend,def{477},use{485},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolDelete,priv,def{476},use{481},dvars{},pointers{volume},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolDelete,flags,def{474},use{485},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolDelete,volume,def{474},use{476,477,479,485},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByKey,volume,def{412,421},use{423,424},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByKey,i,def{414},use{420},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByKey,key,def{410},use{421,430,1351,1361,1370,1380,1692,1697},dvars{ret,volume},pointers{},cfuncs{virReportError{2},virGetStorageVol{4},virStorageVolDefFindByKey{2},storageVolLookupByKey{2}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByKey,priv,def{413},use{416},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByKey,conn,def{410},use{59,61,63,65,84,85,88,90,210,224,413,421,1352,1356,1357,1358,1359,1361,1364,1368,1375,1383,1691,1696,1697,1698,2136,2138,2147},dvars{ret,volume},pointers{},cfuncs{pthread_mutex_lock{1},virMutexLock{1},virStoragePoolObjUnlock{1},virGetStorageVol{2},pthread_mutex_unlock{1},virStorageVolDefFindByKey{1},storageDriverUnlock{1},virStoragePoolObjLock{1},storageDriverLock{1},virMutexUnlock{1},storageVolLookupByKey{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByName,backend,def{365},use{373},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByName,priv,def{364},use{369},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByName,name,def{362},use{373},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByName,pool,def{362},use{364,365,367,373},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXML,backend,def{442},use{450},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXML,priv,def{441},use{446},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXML,flags,def{439},use{450},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXML,xmldesc,def{438},use{450},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXML,pool,def{438},use{441,442,444,450},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolSetAutostart,autostart,def{310,313},use{315},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolSetAutostart,ATTRIBUTE_UNUSED,def{309},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetXMLDesc,backend,def{283},use{291},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetXMLDesc,priv,def{282},use{287},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetXMLDesc,flags,def{280},use{291},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetXMLDesc,pool,def{280},use{282,283,285,291},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetInfo,backend,def{264},use{274},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetInfo,priv,def{263},use{270},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetInfo,info,def{261},use{268,274},dvars{},pointers{},cfuncs{memset{4},memset{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetInfo,pool,def{261},use{263,264,266,274},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolNumOfVolumes,backend,def{330},use{338},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolNumOfVolumes,priv,def{329},use{334},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolNumOfVolumes,pool,def{327},use{329,330,332,338},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,backend,def{460},use{468},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,priv,def{459},use{464},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,flags,def{457},use{468},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,sourceVolume,def{457},use{468},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,xmldesc,def{456},use{468},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolCreateXMLFrom,pool,def{456},use{459,460,462,468},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByVolume,volume,def{236},use{238},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByPath,path,def{379},use{395,396,397,398,401},dvars{},pointers{},cfuncs{virReportError{2}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByPath,priv,def{381},use{383},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolLookupByPath,conn,def{379},use{381,396,398},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfStoragePools,tmp,def{91,98},use{100,104},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfStoragePools,i,def{90},use{97},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfStoragePools,count,def{88},use{104,107},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfStoragePools,priv,def{89},use{93},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfStoragePools,conn,def{86},use{89,98},dvars{tmp},pointers{},cfuncs{connectNumOfStoragePools{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolListVolumes,backend,def{348},use{356},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolListVolumes,priv,def{347},use{352},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolListVolumes,maxnames,def{345},use{356},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolListVolumes,names,def{344},use{356},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolListVolumes,pool,def{344},use{347,348,350,356},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListDefinedStoragePools,ATTRIBUTE_UNUSED,def{165,166,167},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByName,pool,def{180,189},use{191,192},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByName,i,def{179},use{188},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByName,name,def{176},use{182,189,197,266,272,277,284,428,441,450,1649,1655},dvars{ret,pool},pointers{},cfuncs{virGetStoragePool{2},memcpy{2},memcpy{1},virReportError{2},virStoragePoolObjFindByName{2},storagePoolLookupByName{2},virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByName,priv,def{178},use{184},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByName,conn,def{176},use{178,189,268,272,275,281,284,288,289,428,441,450,2147},dvars{ret,pool},pointers{},cfuncs{virCheckNonNullArgReturn{1},memcpy{2},memcpy{1},virStoragePoolObjUnlock{1},virGetStoragePool{3},virGetStoragePool{2},storagePoolLookupByName{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetXMLDesc,backend,def{528},use{536},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetXMLDesc,priv,def{527},use{532},dvars{},pointers{volume},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetXMLDesc,flags,def{525},use{536},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolGetXMLDesc,volume,def{525},use{527,528,530,536},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,uuid_string,def{210},use{225,228},dvars{},pointers{},cfuncs{virReportError{2},virUUIDFormat{2}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,i,def{208},use{217},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,pool,def{209,218},use{220,221},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,uuid,def{205},use{42,44,45,47,209,211,217,218,225},dvars{pool},pointers{},cfuncs{va_end {1},snprintf{1},va_start {1},virUUIDFormat{1},vasnprintf {4},storagePoolLookupByUUID{2}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,priv,def{207},use{212},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolLookupByUUID,conn,def{205},use{59,61,63,65,84,85,88,90,207,210,218,224,238,242,243,244,1632,1637,1638,1639,1640,1641,2136,2138,2147},dvars{pool},pointers{},cfuncs{virStoragePoolObjUnlock{1},virMutexLock{1},virStoragePoolObjLock{1},virMutexUnlock{1},storageDriverUnlock{1},pthread_mutex_unlock{1},storagePoolLookupByUUID{1},pthread_mutex_lock{1},virStoragePoolObjFindByUUID{1},storageDriverLock{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,i,def{118},use{129,143},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,tmp,def{119,130},use{132,136},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,count,def{117,147},use{130,136,143,147,150},dvars{tmp},pointers{},cfuncs{connectListStoragePools{3}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,success,def{115,139},use{142},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,maxnames,def{113},use{121,130},dvars{tmp},pointers{},cfuncs{connectListStoragePools{3}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,names,def{113},use{130,144},dvars{tmp},pointers{},cfuncs{VIR_FREE{1},connectListStoragePools{2}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,priv,def{116},use{125},dvars{},pointers{conn},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectListStoragePools,conn,def{113},use{116,130},dvars{tmp},pointers{},cfuncs{connectListStoragePools{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolRefresh,backend,def{247},use{255},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolRefresh,priv,def{246},use{251},dvars{},pointers{pool},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolRefresh,flags,def{244},use{255},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolRefresh,pool,def{244},use{246,247,249,255},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetAutostart,storagePoolGetXMLDescpoolflagsautostart,def{301},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetAutostart,autostart,def{298},use{301},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStoragePoolGetAutostart,ATTRIBUTE_UNUSED,def{297},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxConnectNumOfDefinedStoragePools,ATTRIBUTE_UNUSED,def{156},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolWipe,backend,def{494},use{502},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolWipe,priv,def{493},use{498},dvars{},pointers{volume},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolWipe,flags,def{491},use{502},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageVolWipe,volume,def{491},use{493,494,496,502},dvars{backend},pointers{},cfuncs{virCheckNonNullArgReturn{1}}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageClose,VIR_DRV_OPEN_SUCCESSconn,def{78},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageClose,conn,def{76},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageOpen,VIR_DRV_OPEN_DECLINEDconn,def{68},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageOpen,flags,def{60},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageOpen,ATTRIBUTE_UNUSED,def{59},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/esx/esx_storage_driver.c,esxStorageOpen,conn,def{58},use{64,68},dvars{VIR_DRV_OPEN_DECLINEDconn},pointers{},cfuncs{}
