libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ProcessorList,list,def{106},use{112},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ProcessorList,query,def{106},use{108},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ProcessorList,priv,def{106},use{108},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ComputerSystemList,list,def{90},use{96},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ComputerSystemList,query,def{90},use{92},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetWin32ComputerSystemList,priv,def{90},use{92},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmProcessorSettingDataList,list,def{58},use{64},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmProcessorSettingDataList,query,def{58},use{60},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmProcessorSettingDataList,priv,def{58},use{60},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmMemorySettingDataList,list,def{42},use{48},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmMemorySettingDataList,query,def{42},use{44},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmMemorySettingDataList,priv,def{42},use{44},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmConcreteJobList,list,def{26},use{32},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmConcreteJobList,query,def{26},use{28},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmConcreteJobList,priv,def{26},use{28},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmVirtualSystemSettingDataList,list,def{74},use{80},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmVirtualSystemSettingDataList,query,def{74},use{76},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmVirtualSystemSettingDataList,priv,def{74},use{76},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmComputerSystemList,list,def{10},use{16},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmComputerSystemList,query,def{10},use{12},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.generated.c,hypervGetMsvmComputerSystemList,priv,def{10},use{12},dvars{},pointers{},cfuncs{}
