libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,conn,def{110},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,computerSystem,def{105,107,111,115},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,requestedState,def{102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,domain,def{101,112,114},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,className,def{54},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,query,def{52},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,resourceUri,def{54},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,list,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,serializerInfo,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,root,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,priv,def{52,57},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,in_transition,def{108},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,object,def{57},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,returnCode,def{93},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,response,def{37},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,detail,def{38},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/hyperv/hyperv_wmi.h,GLOBAL,client,def{37},use{},dvars{},pointers{},cfuncs{}
