libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolCreateLockSpaceArgs,objp,def{145},use{148},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolCreateLockSpaceArgs,xdrs,def{145},use{148},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolReleaseResourceArgs,objp,def{132},use{135,137,139},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolReleaseResourceArgs,xdrs,def{132},use{135,137,139},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolAcquireResourceFlags,objp,def{110},use{113},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolAcquireResourceFlags,xdrs,def{110},use{113},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolUUID,objp,def{11},use{14},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolUUID,xdrs,def{11},use{14},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolDeleteResourceArgs,objp,def{97},use{100,102,104},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolDeleteResourceArgs,xdrs,def{97},use{100,102,104},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolString,objp,def{29},use{32},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolString,xdrs,def{29},use{32},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolRegisterArgs,objp,def{53},use{56,58},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolRegisterArgs,xdrs,def{53},use{56,58},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolProcedure,objp,def{154},use{157},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolProcedure,xdrs,def{154},use{157},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolCreateResourceArgs,objp,def{84},use{87,89,91},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolCreateResourceArgs,xdrs,def{84},use{87,89,91},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolRestrictArgs,objp,def{64},use{67},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolRestrictArgs,xdrs,def{64},use{67},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolOwner,objp,def{38},use{41,43,45,47},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolOwner,xdrs,def{38},use{41,43,45,47},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolAcquireResourceArgs,objp,def{119},use{122,124,126},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolAcquireResourceArgs,xdrs,def{119},use{122,124,126},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolNewArgs,objp,def{73},use{76,78},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolNewArgs,xdrs,def{73},use{76,78},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolNonNullString,objp,def{20},use{23},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/locking/lock_protocol.c,xdr_virLockSpaceProtocolNonNullString,xdrs,def{20},use{23},dvars{},pointers{},cfuncs{}
