libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,def,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,net,def{52,56},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,doms,def{48},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,reason,def{31,34},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,driver,def{28,32,36,37,39,40,43,46,47},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,autoDestroy,def{30},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,brname,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,vm,def{29,33,41,44,51},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_process.h,GLOBAL,conn,def{27,38,42,50,54},use{},dvars{},pointers{},cfuncs{}
