libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDeviceDefPostParse,ATTRIBUTE_UNUSED,def{101,102,103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDeviceDefPostParse,dev,def{100,108},use{105,106,107},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLParse,err,def{68},use{69},dvars{},pointers{},cfuncs{VIR_WARN{2}}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLParse,priv,def{64,70,72},use{70},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLParse,data,def{62},use{64},dvars{priv},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLParse,thepid,def{65},use{67,72},dvars{priv},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLParse,ctxt,def{62},use{67},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLFormat,priv,def{54},use{57,290},dvars{},pointers{},cfuncs{virBufferAsprintf{3}}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLFormat,data,def{52},use{54},dvars{priv},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateXMLFormat,buf,def{52},use{56,292,293,294,295},dvars{},pointers{},cfuncs{va_end{1},virBufferVasprintf{3},va_start{1},virBufferAsprintf{1}}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateFree,priv,def{44},use{46,48,75,79,83,84,85,88,89},dvars{},pointers{},cfuncs{VIR_FREE{1},virCgroupFree{1}}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateFree,data,def{42},use{44},dvars{priv},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateAlloc,priv,def{34},use{36,39},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainObjPrivateAlloc,,def{32},use{36},dvars{},pointers{},cfuncs{VIR_ALLOC{1}}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDefPostParse,defemulatordefemulator,def{92},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDefPostParse,ATTRIBUTE_UNUSED,def{88},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDefPostParse,caps,def{87},use{92},dvars{defemulatordefemulator},pointers{},cfuncs{}
libvirt-1.1.0/src/lxc/lxc_domain.c,virLXCDomainDefPostParse,def,def{86},use{92},dvars{defemulatordefemulator},pointers{},cfuncs{}
