libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,dev,def{58,59,60,61,64},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,wwpn,def{56},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,flags,def{47,49,52,57,58,63},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,wwnn,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,xmlDesc,def{63},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,maxnames,def{49,61},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,d,def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,devices,def{51},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,names,def{48,61},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,name,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,cap,def{47,48},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,conn,def{47,48,50,53,54,62},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,driver,def{40,41},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/node_device/node_device_driver.h,GLOBAL,,def{34,37,43},use{},dvars{},pointers{},cfuncs{}
