libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,hash,def{139,160},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,varAccess,def{127,130},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,src,def{88},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,freeName,def{85},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,b,def{61,91,129},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,n,def{80},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,vars,def{161},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,filterref,def{78},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,nVars,def{162},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,name,def{83,87},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,cur,def{75},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,ci,def{164,166,167},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,value,def{62,63},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,val,def{55,56,57,62,63,84},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,a,def{60,90,128},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,idx,def{58},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,dest,def{89},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,table,def{77,81,82,86},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,vap,def{131,133,135,136,137,138},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,buf,def{76,132},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/nwfilter_params.h,GLOBAL,,def{52,53,54,59,168},use{},dvars{},pointers{},cfuncs{}
