libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,skipauth,def{236},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,state,def{231},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,file,def{227},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,passphrase,def{211},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,driveAddr,def{192},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,controllerAddr,def{191},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,drivestr,def{190,204,207},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,alias,def{180,210},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,netdevstr,def{177},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,netname,def{174},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,product,def{143},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,tlsSubject,def{133},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,tlsPort,def{132},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,info,def{240},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,port,def{131},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,type,def{129},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,uri,def{124},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,downtime,def{117},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,netstr,def{170},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,fdname,def{163,167,235},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,offset,def{105,109},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,bandwidth,def{114},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,hostname,def{130},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,size,def{81},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,data,def{33},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,format,def{101},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,newmedia,def{100},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,reply,def{40,218,244},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,online,def{93},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,newmem,def{92},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,path,def{107,111,136,151},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,fd,def{164},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,scm_fd,def{39},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,password,def{83,86},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,nkeycodes,def{225},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,paths,def{183},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,rd_bytes,def{66},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,device,def{80,239,243},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,keycodes,def{224},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,rd_total_times,def{67},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,extent,def{78},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,nparams,def{75},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,flush_total_times,def{72},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,expire_time,def{90},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,rd_req,def{65},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,length,def{106,110},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,errs,def{73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,vendor,def{142},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,bus,def{139,152,186},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,cpu,def{93},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,pids,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,wr_total_times,def{70},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,name,def{213,214,215,230},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,devalias,def{201},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,vlan,def{173},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,wr_bytes,def{69},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,cmd,def{38,217},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,dev_name,def{64,77,96,99},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,devicestr,def{198},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,status,def{120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,table,def{62},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,wr_req,def{68},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,protocol,def{85,89,234},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,conn,def{43},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,nr_stats,def{60},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,dev,def{140},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,currmem,def{57},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,guestAddr,def{148,153,157,160,187},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,virtType,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,addrs,def{195},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,force,def{97},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,stats,def{59},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,len,def{34},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,hostAddr,def{147},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,running,def{46},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,flags,def{123},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,holdtime,def{223},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,flush_req,def{71},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,msg,def{35},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,reason,def{47},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,nicstr,def{156},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,action_if_connected,def{87},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/qemu/qemu_monitor_text.h,GLOBAL,mon,def{32,37,42,44,45,49,50,52,54,56,58,61,63,74,76,79,82,84,88,91,93,95,98,104,108,113,116,119,122,126,128,135,138,141,146,150,155,159,162,166,169,172,176,179,182,185,189,194,197,200,203,206,209,213,214,215,217,220,222,227,229,233,238,242},use{},dvars{},pointers{},cfuncs{}
