libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetMountOptions,ATTRIBUTE_UNUSED,def{507,508},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,i,def{518},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,len,def{518},use{521,523},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,item,def{517},use{520,528,529},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,list,def{515,529,530},use{523,532},dvars{},pointers{item},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,priv,def{516},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetNested,mgr,def{513},use{215,217,516},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,rc,def{497,501},use{501,504},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,item,def{496},use{499,500},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,path,def{493},use{500},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,priv,def{495},use{496},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,vm,def{492},use{500},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetHugepages,mgr,def{491},use{215,217,495},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,item,def{479},use{482,483},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,rc,def{480,484},use{484,487},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,fd,def{476},use{483},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,priv,def{478},use{479},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,vm,def{475},use{483},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetTapFDLabel,mgr,def{474},use{215,217,478},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,item,def{462},use{465,466},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,rc,def{463,467},use{467,470},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,fd,def{459},use{466},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,priv,def{461},use{462},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,vm,def{458},use{466},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetImageFDLabel,mgr,def{457},use{215,217,461},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSocketLabel,rc,def{429,433},use{433,436},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSocketLabel,item,def{428},use{431,432},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSocketLabel,priv,def{427},use{428},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSocketLabel,vm,def{425},use{432},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSocketLabel,mgr,def{424},use{215,217,427},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetDaemonSocketLabel,rc,def{412,416},use{416,419},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetDaemonSocketLabel,item,def{411},use{414,415},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetDaemonSocketLabel,priv,def{410},use{411},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetDaemonSocketLabel,vm,def{408},use{415},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetDaemonSocketLabel,mgr,def{407},use{215,217,410},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,rc,def{376,380},use{380,383},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,item,def{375},use{378,379},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,vm,def{371},use{379},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,cmd,def{372},use{379},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,priv,def{374},use{375},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetChildProcessLabel,mgr,def{370},use{215,217,374},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetProcessLabel,rc,def{359,363},use{363,366},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetProcessLabel,item,def{358},use{361,362},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetProcessLabel,priv,def{357},use{358},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetProcessLabel,vm,def{355},use{362},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetProcessLabel,mgr,def{354},use{215,217,357},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClearSocketLabel,rc,def{446,450},use{450,453},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClearSocketLabel,item,def{445},use{448,449},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClearSocketLabel,priv,def{444},use{445},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClearSocketLabel,vm,def{442},use{449},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClearSocketLabel,mgr,def{441},use{215,217,444},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,rc,def{342,346},use{346,349},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,item,def{341},use{344,345},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,savefile,def{338},use{345},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,priv,def{340},use{341},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,vm,def{337},use{345},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSavedStateLabel,mgr,def{336},use{215,217,340},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGenLabel,rc,def{139,142},use{142,156},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGenLabel,vm,def{137},use{141},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGenLabel,mgr,def{136},use{141},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,rc,def{288,292},use{292,295},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,item,def{287},use{290,291},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,stdin_path,def{284},use{291},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,priv,def{286},use{287},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,vm,def{283},use{291},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityAllLabel,mgr,def{282},use{215,217,286},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetModel,mgr,def{105},use{107},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetProcessLabel,rc,def{392,400},use{400,402},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetProcessLabel,seclabel,def{390},use{399},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetProcessLabel,pid,def{389},use{399},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetProcessLabel,vm,def{388},use{399},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetProcessLabel,mgr,def{387},use{399},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClose,item,def{92,98},use{94,95,96,97,254,256,258,259,260,262,263,266,271,272,273,274,338,343},dvars{klass,is_zero,next},pointers{},cfuncs{memset{3},memset{1},dispose{1},virAtomicIntDecAndTest{1},PROBE{3},VIR_FREE{1},virObjectUnref{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClose,next,def{92,95},use{98},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClose,priv,def{91},use{92},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackClose,mgr,def{89},use{91,215,217},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,tmp,def{50,54,62},use{53,61},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,item,def{48,60},use{56,62,64},dvars{priv,tmp},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,nested,def{46},use{60},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,priv,def{49,64},use{52},dvars{optstmp},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,optstmp,def{52},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackAddNested,mgr,def{45},use{49,215,217},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,rc,def{267,274},use{274,277},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,item,def{266},use{269,270},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,dev,def{262},use{272},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,priv,def{265},use{266},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,mgr,def{260},use{215,217,265},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,vroot,def{263},use{273},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityHostdevLabel,vm,def{261},use{271},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,rc,def{225,229},use{229,232},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,item,def{224},use{227,228},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,disk,def{221},use{228},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,priv,def{223},use{224},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,vm,def{220},use{228},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityImageLabel,mgr,def{219},use{215,217,223},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReleaseLabel,rc,def{164,167},use{167,176},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReleaseLabel,vm,def{162},use{166},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReleaseLabel,mgr,def{161},use{166},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReserveLabel,rc,def{185,188},use{188,196},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReserveLabel,pid,def{183},use{187},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReserveLabel,vm,def{182},use{187},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackReserveLabel,mgr,def{181},use{187},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetDOI,mgr,def{111},use{113},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackVerify,rc,def{122,126},use{126,131},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackVerify,item,def{121},use{124,125},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackVerify,def,def{118},use{125},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackVerify,priv,def{120},use{121},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackVerify,mgr,def{117},use{120,215,217},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetPrimary,priv,def{72},use{73},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackGetPrimary,mgr,def{70},use{72,215,217},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,rc,def{306,310},use{310,313},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,item,def{305},use{308,309},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,priv,def{304},use{305},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,migrated,def{302},use{309},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,vm,def{301},use{309},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackRestoreSecurityAllLabel,mgr,def{300},use{215,217,304},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,rc,def{245,252},use{252,255},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,item,def{244},use{247,248},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,dev,def{239},use{250},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,priv,def{243},use{244},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,mgr,def{237},use{215,217,243},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,vroot,def{240},use{251},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityHostdevLabel,vm,def{238},use{249},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackOpen,ATTRIBUTE_UNUSED,def{83},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,rc,def{207,211},use{211,214},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,item,def{206},use{209,210},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,disk,def{203},use{210},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,priv,def{205},use{206},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,vm,def{202},use{210},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSecurityImageLabel,mgr,def{201},use{205,215,217},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,rc,def{324,328},use{328,331},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,item,def{323},use{326,327},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,savefile,def{320},use{327},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,priv,def{322},use{323},dvars{item},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,vm,def{319},use{327},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackSetSavedStateLabel,mgr,def{318},use{215,217,322},dvars{},pointers{},cfuncs{virSecurityManagerGetPrivateData{1}}
libvirt-1.1.0/src/security/security_stack.c,virSecurityStackProbe,ATTRIBUTE_UNUSED,def{77},use{},dvars{},pointers{},cfuncs{}
