libvirt-1.1.0/src/security/security_manager.h,GLOBAL,pid,def{92,103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,sec,def{89,91,94,96,104,123},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,migrated,def{100},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,dev,def{76,80},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,cmd,def{109},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,dynamicOwnership,def{48},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,disk,def{64,73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,stdin_path,def{97},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,requireConfined,def{36,47},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,group,def{44},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,fd,def{114,117},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,vm,def{66,116,119},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,vroot,def{77,81},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,name,def{32},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,virtDriver,def{33,42},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,defaultConfined,def{35,46},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,stack,def{39},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,user,def{43},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,def,def{63,68,70,72,75,79,83,86,99,102,106,108,111,113},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,primary,def{38},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,nested,def{40},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,hugepages_path,def{124},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,allowDiskFormatProbing,def{34,45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,savefile,def{84,87},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/security/security_manager.h,GLOBAL,mgr,def{50,51,53,55,56,57,58,59,60,62,65,67,69,71,74,78,82,85,88,90,93,95,98,101,105,107,110,112,115,118,121,122},use{},dvars{},pointers{},cfuncs{}
