libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,snaps,def{167},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,dom,def{166},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,from,def{119,123,165},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,maxnames,def{120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,require_match,def{114},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,default_snapshot,def{113},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,names,def{120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,snapshots,def{93,115,118,122,125,127,129,138,164},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,snapshot,def{112,128,132,135,139},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,data,def{131,134,137},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,domain_uuid,def{108},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,iter,def{130,133,136},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,def,def{107,109,116,170},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,snap,def{171},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,name,def{126},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,expectedVirtTypes,def{105},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,flags,def{106,110,121,124,168},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,caps,def{103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,xmlStr,def{102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,internal,def{111},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,xmlopt,def{104},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/conf/snapshot_conf.h,GLOBAL,,def{92},use{},dvars{},pointers{},cfuncs{}
