libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayRelease,supports,def{340,347},use{349,350},dvars{},pointers{mediumAttachments,children,machines,deviceFilters,storageControllers,sharedFolders,hardDisks,hddAttachments,networkInterfaces,array},cfuncs{Release{1}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayRelease,i,def{339},use{346},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayRelease,array,def{337,356,357},use{342,346,347,354,357},dvars{},pointers{},cfuncs{pfnComUnallocMem{1}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,vboxArrayGetHelperarraynsrcitemscountnsrc,def{328},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,count,def{326},use{328,330},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,items,def{325},use{328,330},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,nsrc,def{324},use{330},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,arg,def{322},use{328},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,getter,def{322},use{328},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{machine},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,self,def{322},use{328},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{machine},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithUintArg,array,def{322},use{330},dvars{},pointers{media},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,vboxArrayGetHelperarraynsrcitemscountnsrc,def{312},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,count,def{310},use{312,314},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,items,def{309},use{312,314},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,nsrc,def{308},use{314},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,arg,def{306},use{312},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{strCtlName},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,getter,def{306},use{312},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{machine},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,self,def{306},use{312},dvars{vboxArrayGetHelperarraynsrcitemscountnsrc},pointers{machine},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetWithPtrArg,array,def{306},use{314},dvars{},pointers{mediumAttachments},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueInit,home,def{206},use{209,210},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueInit,knownDirs,def{190},use{223,224},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueInit,i,def{189},use{223},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueInit,version,def{187},use{210,217,224,230},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayUnalloc,i,def{366},use{373},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayUnalloc,item,def{367,374},use{376,377},dvars{},pointers{media,machineIds,array},cfuncs{pfnComUnallocMem{1}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayUnalloc,array,def{364,383,384},use{369,373,374,381,384},dvars{},pointers{},cfuncs{pfnComUnallocMem{1}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,hVBoxXPCOMC,def{127,171},use{129,142,169,170},dvars{pfnGetFunctions},pointers{},cfuncs{dlclose{1},dlsym{1}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,g_pfnGetFunctions,def{159},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,pfnGetFunctions,def{94,141},use{144,150,159},dvars{g_pfnGetFunctions,pVBoxFuncs_v2_2},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,name,def{93},use{97,102,104,107,111,127,135,146,154,174},dvars{hVBoxXPCOMC},pointers{},cfuncs{VIR_WARN{2},dlopen{1},VIR_ERROR{3},VIR_FREE{1},VIR_ERROR{2}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,result,def{92,160},use{160,169,176},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,version,def{90,158},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,pVBoxFuncs_v2_2,def{150},use{152,158},dvars{version},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,ignoreMissing,def{89},use{103},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,setAppHome,def{89},use{119},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,tryLoadOne,dir,def{89},use{96,97,120,121,134,162,163,291,299},dvars{},pointers{},cfuncs{VIR_DEBUG{3},setenv{2}}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,nsrcnsrc,def{296},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,count,def{294},use{296,298},dvars{nsrcnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,items,def{293},use{296,298},dvars{nsrcnsrc},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,nsrc,def{292},use{298},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,getter,def{290},use{296},dvars{nsrcnsrc},pointers{machine,USBController,hardDisk,list,snapshot,data},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,self,def{290},use{296},dvars{nsrcnsrc},pointers{machine,USBController,hardDisk,list,snapshot,data},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGet,array,def{290},use{298},dvars{},pointers{mediumAttachments,children,networkInterfaces,machines,deviceFilters,storageControllers,sharedFolders,hardDisks,machineIds,hddAttachments},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetHelper,nsrcarray,def{279},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetHelper,count,def{270},use{273,280},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetHelper,items,def{270},use{279},dvars{nsrcarray},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetHelper,nsrc,def{270},use{275,276,282},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,vboxArrayGetHelper,array,def{270,272,273,280},use{273},dvars{},pointers{count},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,items,def{265,266,267},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,count,def{265,266,267},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,self,def{265,266,267},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,g_pfnGetFunctions,def{253},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,pVBoxFuncs_v2_2,def{252},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,arg,def{266,267},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,hVBoxXPCOMC,def{249},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/vbox/vbox_XPCOMCGlue.c,VBoxCGlueTerm,,def{243},use{},dvars{},pointers{},cfuncs{}
