libvirt-1.1.0/src/util/virerror.h,GLOBAL,theerrno,def{58,162},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,errBufLen,def{162},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,errcode,def{50},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,domcode,def{50,57,148},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,str3,def{44},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,str1,def{42},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,func,def{165},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,fmt,def{47,54,62},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,level,def{41},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,conn,def{161},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,int1,def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,code,def{40},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,errBuf,def{162},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,int2,def{46},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,domain,def{39},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,linenr,def{38,53,61,151},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,str2,def{43},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,newerr,def{160},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,funcname,def{37,52,60,150},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,filename,def{36,51,59,149},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virerror.h,GLOBAL,,def{35,47,54,62,65,71,82,93,104,115,126,137,156,164},use{},dvars{},pointers{},cfuncs{}
