libvirt-1.1.0/src/util/virfile.h,GLOBAL,msg,def{232},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,fp,def{232},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,type,def{223},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,ttyName,def{220},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,checkLink,def{142},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,suffix,def{134,137},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,name,def{133},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,str,def{136},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,readonly,def{120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,fmt,def{119},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,mode_remove,def{112},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,dir,def{123},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,file,def{115,118,132,153,155,156,157},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,rawmode,def{221},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,rewrite,def{106},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,checkDest,def{143},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,mode,def{105,109},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,mode_add,def{113},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,fd,def{100,101,103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,path,def{104,109,111,159,214,217},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,opaque,def{103,107},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,len,def{100,101},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,dev,def{116,121},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,shared,def{100},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,ttymaster,def{219},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,start,def{100,101},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,dfd,def{96,98},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virfile.h,GLOBAL,,def{54,55,58,62,64,68,73,84,200,208,225,228,232},use{},dvars{},pointers{},cfuncs{}
