libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,func,def{151},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,len,def{124,125},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,pid,def{116},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,gid,def{115},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,uid,def{114},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,object,def{100},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,knownHostsVerify,def{90},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,privkey,def{88},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,port,def{85},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,netcat,def{79},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,backlog,def{145},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,context,def{119},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,username,def{76,86},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,grp,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,retsock,def{71,94},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,keyfile,def{80},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,buf,def{124,125},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,binary,def{67,75},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,clientsock,def{147},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,sess,def{132,137},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,spawnDaemon,def{66},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,password,def{87},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,path,def{52,65,81},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,addr,def{56,59,63,68,82,97},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,fd,def{58,127,128},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,user,def{54},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,mask,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,naddrs,def{50},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,cmdargv,def{96},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,auth,def{93},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,noTTY,def{77},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,cmd,def{70},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,authMethods,def{91},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,opaque,def{44,152},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,host,def{84},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,addrs,def{49},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,timestamp,def{117},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,events,def{43,150,156},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,blocking,def{122},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,cloexec,def{105},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,knownHosts,def{89},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,service,def{48,62,74},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,ff,def{153},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,command,def{92},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,noVerify,def{78},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,nodename,def{47,61,73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetsocket.h,GLOBAL,sock,def{42,102,104,105,107,109,111,113,118,121,124,125,127,128,131,136,139,140,142,143,145,146,149,155,158,160},use{},dvars{},pointers{},cfuncs{}
