libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,count,def{131},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,interval,def{130},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,context,def{106},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,uid,def{102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,privOpaque,def{62,68},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,pid,def{102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,privFree,def{61,67},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,filterID,def{77},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,privPreExecRestart,def{60,66},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,func,def{73,118},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,sasl,def{91},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,privNew,def{59,65},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,tls,def{57},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,auth,def{53,80},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,nrequests_max,def{55},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,data,def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,timestamp,def{103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,client,def{36,40,44,46,49,70,72,76,79,80,81,84,85,86,90,92,95,97,99,101,105,108,110,112,114,117,120,121,123,124,125,127,129,132,134,136,137,139,142},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,opaque,def{38,42,48,50,74,119},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,sock,def{52},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,gid,def{102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,readonly,def{54},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,msg,def{37,41,133,140},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,cf,def{115},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/rpc/virnetserverclient.h,GLOBAL,object,def{47,64},use{},dvars{},pointers{},cfuncs{}
