libvirt-1.1.0/src/util/virpci.h,GLOBAL,pfname,def{168},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,vf_sysfs_device_path,def{167},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,bdf,def{165},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,netname,def{152},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,vf_index,def{147,168},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,vf_sysfs_device_link,def{143,146},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,address,def{165},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,virtual_functions,def{140},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,phys_fn,def{137},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,matcher,def{134},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,nIommuGroupDevices,def{128},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,bus,def{45,101},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,orig,def{122},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,actor,def{117,123},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,list,def{84,86,87,89,90,92,94,96,99,104},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,opaque,def{115,118,121,124},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,iommuGroupDevices,def{127},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,,def{83},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,reprobe,def{79},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,slot,def{46,102},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,unbind,def{73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,dev,def{48,49,50,52,55,58,62,64,65,67,68,70,71,72,74,75,77,78,80,85,86,91,95,97,105,114,116,125,129,130,132,134,149},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,device_link_sysfs_path,def{152},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,managed,def{63},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,num_virtual_functions,def{141},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,inactiveDevs,def{54,57,60},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,pci_sysfs_device_link,def{150},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,remove_slot,def{76},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,driver,def{66},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,sysfs_path,def{136,139},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,idx,def{88,93},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,activeDevs,def{53,56,59},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,devAddr,def{126},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,strict_acs_check,def{133},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,function,def{47,103},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,addr,def{120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,path,def{115},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,used_by,def{69},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,pf_sysfs_device_link,def{145},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virpci.h,GLOBAL,domain,def{44,100},use{},dvars{},pointers{},cfuncs{}
