libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,s2,def{123},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,address,def{119},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,s1,def{122},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,broadcast,def{110,113},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,addr2,def{100},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,addr1,def{99},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,netmask,def{97,101,103,109,115,117,120},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,end,def{95},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,port,def{90},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,separator,def{88},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,withService,def{87},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,family,def{75,118},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,start,def{94},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,val,def{74,78,81},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,s,def{83},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,addr,def{73,77,80,83,85,86,90,92,102,105,108,111,124,126},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,prefix,def{106,112,116,121},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,network,def{104,107},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virsocketaddr.h,GLOBAL,,def{48,51,54},use{},dvars{},pointers{},cfuncs{}
