libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalGet,l,def{265},use{267},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalInit,errno,def{259},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalInit,ret,def{257,258},use{259},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalInit,c,def{255},use{258},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalInit,l,def{254},use{258},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadJoin,thread,def{244},use{169,246},dvars{},pointers{},cfuncs{pthread_join{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelfID,l,def{223},use{227},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelfID,t,def{224},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelfID,tid,def{219},use{220},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelfID,truefalsetidu,def{226},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelfID,,def{216},use{218,227},dvars{},pointers{},cfuncs{defined{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCancel,thread,def{249},use{251},dvars{},pointers{},cfuncs{pthread_cancel{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondDestroy,errno,def{108},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondDestroy,ret,def{106,107},use{108},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondDestroy,c,def{104},use{107},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondInit,errno,def{98},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondInit,ret,def{96,97},use{98},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondInit,c,def{94},use{97},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadIsSelf,thread,def{208},use{210},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,errno,def{199},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,ret,def{172,195},use{195,198,200},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,NULLerr,def{175},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,err,def{173,178,188},use{189,199},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,attr,def{171},use{175,186,188,197},dvars{err,NULLerr},pointers{},cfuncs{pthread_attr_destroy{1},pthread_create{2},pthread_attr_setdetachstate{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,thread,def{165},use{188},dvars{err},pointers{},cfuncs{pthread_create{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,joinable,def{166},use{185},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,func,def{167},use{182},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,args,def{170,182,183},use{177,188,190},dvars{err},pointers{opaque,func},cfuncs{VIR_FREE{1},pthread_create{4}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadCreate,opaque,def{168},use{183,188},dvars{err},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadHelper,local,def{157},use{161},dvars{},pointers{},cfuncs{func{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadHelper,args,def{156},use{157,160},dvars{local},pointers{data},cfuncs{VIR_FREE{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadHelper,data,def{154},use{156},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,errno,def{133},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,whenms,def{124},use{129,130},dvars{ts},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,ts,def{127,129,130},use{132},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,m,def{124},use{132},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,ret,def{126,132},use{133},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWaitUntil,c,def{124},use{132},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexUnlock,m,def{88},use{90,224},dvars{},pointers{m},cfuncs{pthread_mutex_unlock{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexDestroy,m,def{79},use{81,195},dvars{},pointers{m},cfuncs{pthread_mutex_destroy{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInitRecursive,errno,def{73},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInitRecursive,ret,def{66,70},use{72,73},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInitRecursive,attr,def{67},use{68,69,70,71,177,183,189,203},dvars{ret},pointers{},cfuncs{pthread_mutexattr_destroy{1},pthread_mutex_init{2},pthread_mutexattr_settype{1},pthread_mutexattr_init{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInitRecursive,m,def{64},use{70,202},dvars{ret},pointers{},cfuncs{pthread_mutex_init{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondBroadcast,c,def{144},use{146},dvars{},pointers{},cfuncs{pthread_cond_broadcast{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalSet,errno,def{274},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalSet,err,def{272},use{273,274},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalSet,val,def{270},use{272},dvars{},pointers{},cfuncs{pthread_setspecific{2}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadLocalSet,l,def{270},use{272},dvars{},pointers{},cfuncs{pthread_setspecific{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexLock,m,def{84},use{85,210},dvars{},pointers{m},cfuncs{pthread_mutex_lock{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadID,lu,def{240},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadID,t,def{238},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadID,l,def{237},use{241},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadID,thread,def{234},use{240},dvars{lu},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virOnce,init,def{43},use{45},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virOnce,once,def{43},use{45},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadOnExit,,def{39},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadInitialize,,def{34},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInit,errno,def{58},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInit,ret,def{51,55},use{57,58},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInit,attr,def{52},use{53,54,55,56,177,183,189,203},dvars{ret},pointers{attr},cfuncs{pthread_mutexattr_destroy{1},pthread_mutex_init{2},pthread_mutexattr_settype{1},pthread_mutexattr_init{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virMutexInit,m,def{49},use{55,202},dvars{ret},pointers{},cfuncs{pthread_mutex_init{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelf,retthread,def{205},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virThreadSelf,thread,def{203},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondSignal,c,def{139},use{137,141},dvars{},pointers{c},cfuncs{pthread_cond_signal{1}}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWait,errno,def{118},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWait,m,def{114},use{117},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWait,ret,def{116,117},use{118},dvars{errno},pointers{},cfuncs{}
libvirt-1.1.0/src/util/virthreadpthread.c,virCondWait,c,def{114},use{117},dvars{ret},pointers{},cfuncs{}
