libvirt-1.1.0/python/typewrappers.c,libvirt_virVoidPtrWrap,ret,def{515},use{523},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virVoidPtrWrap,Py_Noneret,def{522},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virVoidPtrWrap,node,def{513},use{26,33,35,517,522},dvars{Py_Noneret},pointers{opaque},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virFreeCallbackWrap,ret,def{501},use{509},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virFreeCallbackWrap,Py_Noneret,def{508},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virFreeCallbackWrap,node,def{499},use{26,33,35,503,508},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStreamPtrWrap,ret,def{443},use{451},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStreamPtrWrap,Py_Noneret,def{450},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStreamPtrWrap,node,def{441},use{26,33,35,445,450},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNWFilterPtrWrap,ret,def{429},use{437},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNWFilterPtrWrap,Py_Noneret,def{436},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNWFilterPtrWrap,node,def{427},use{26,33,35,431,436},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virSecretPtrWrap,ret,def{415},use{423},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virSecretPtrWrap,Py_Noneret,def{422},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virSecretPtrWrap,node,def{413},use{26,33,35,417,422},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNodeDevicePtrWrap,ret,def{401},use{409},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNodeDevicePtrWrap,Py_Noneret,def{408},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNodeDevicePtrWrap,node,def{399},use{26,33,35,403,408},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virConnectPtrWrap,ret,def{387},use{395},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virConnectPtrWrap,Py_Noneret,def{394},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virConnectPtrWrap,node,def{385},use{26,33,35,389,394},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStorageVolPtrWrap,ret,def{373},use{381},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStorageVolPtrWrap,Py_Noneret,def{380},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStorageVolPtrWrap,node,def{371},use{26,33,35,375,380},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStoragePoolPtrWrap,ret,def{359},use{367},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStoragePoolPtrWrap,Py_Noneret,def{366},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virStoragePoolPtrWrap,node,def{357},use{26,33,35,361,366},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virInterfacePtrWrap,ret,def{345},use{353},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virInterfacePtrWrap,Py_Noneret,def{352},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virInterfacePtrWrap,node,def{343},use{26,33,35,347,352},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainPtrWrap,ret,def{317},use{325},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainPtrWrap,Py_Noneret,def{324},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainPtrWrap,node,def{315},use{26,33,35,319,324},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_doubleUnwrap,double_val,def{282,289},use{290,293},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_doubleUnwrap,val,def{280,293},use{},dvars{},pointers{temp,val},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_doubleUnwrap,obj,def{280},use{284,289},dvars{double_val},pointers{},cfuncs{PyFloat_AsDouble{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_uintUnwrap,long_val,def{157,164},use{165,168,169},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_uintUnwrap,val,def{155,169},use{},dvars{},pointers{temp,val},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_uintUnwrap,obj,def{155},use{159,164},dvars{long_val},pointers{},cfuncs{PyInt_AsLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongUnwrap,llong_val,def{223,234},use{238,241},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongUnwrap,val,def{221,241},use{},dvars{},pointers{temp,val},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongUnwrap,obj,def{221},use{225,233,234},dvars{llong_val},pointers{},cfuncs{PyLong_AsLongLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_longUnwrap,long_val,def{181,188},use{189,192},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longUnwrap,val,def{179,192},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longUnwrap,obj,def{179},use{183,188},dvars{long_val},pointers{},cfuncs{PyInt_AsLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNetworkPtrWrap,ret,def{331},use{339},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNetworkPtrWrap,Py_Noneret,def{338},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virNetworkPtrWrap,node,def{329},use{26,33,35,333,338},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongUnwrap,llong_val,def{249,260},use{261,265},dvars{ullong_val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongUnwrap,ullong_val,def{248,265,267},use{272,275},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongUnwrap,val,def{246,275},use{},dvars{},pointers{temp,val},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongUnwrap,obj,def{246},use{251,259,260,266,267},dvars{ullong_val,llong_val},pointers{},cfuncs{PyLong_AsUnsignedLongLong{1},PyInt_AsLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventHandleCallbackWrap,ret,def{471},use{480},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventHandleCallbackWrap,Py_Noneret,def{479},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventHandleCallbackWrap,node,def{469},use{26,33,35,473,479},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_longWrap,retret,def{53},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longWrap,ret,def{52},use{54},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longWrap,val,def{50},use{53},dvars{retret},pointers{},cfuncs{PyInt_FromLong{1}}
libvirt-1.1.0/python/typewrappers.c,GLOBAL,,def{22},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_constcharPtrWrap,ret,def{112},use{119},dvars{},pointers{local,disks,remote},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_constcharPtrWrap,Py_Noneret,def{118},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_constcharPtrWrap,str,def{110},use{114,118},dvars{Py_Noneret},pointers{stats,params},cfuncs{PyString_FromString{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrWrap,ret,def{98},use{106},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrWrap,Py_Noneret,def{104},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrWrap,str,def{96},use{100,104,105},dvars{Py_Noneret},pointers{},cfuncs{VIR_FREE{1},PyString_FromString{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_boolUnwrap,val,def{298},use{},dvars{},pointers{val},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_boolUnwrap,retval,def{310},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_boolUnwrap,ret,def{300,307},use{308,310},dvars{retval},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_boolUnwrap,obj,def{298},use{302,307},dvars{ret},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_buildPyObject,ret,def{30,33,35},use{38},dvars{},pointers{destr,name,cobj},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_buildPyObject,destr,def{28},use{33,35},dvars{ret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{3},PyCapsule_New{3}}
libvirt-1.1.0/python/typewrappers.c,libvirt_buildPyObject,name,def{27},use{33,35},dvars{ret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{2},PyCapsule_New{2}}
libvirt-1.1.0/python/typewrappers.c,libvirt_buildPyObject,cobj,def{26},use{33,35},dvars{},pointers{node},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventTimeoutCallbackWrap,ret,def{486},use{495},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventTimeoutCallbackWrap,Py_Noneret,def{494},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virEventTimeoutCallbackWrap,node,def{484},use{26,33,35,488,494},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrSizeWrap,ret,def{84},use{92},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrSizeWrap,size,def{82},use{90},dvars{Py_Noneret},pointers{},cfuncs{PyString_FromStringAndSize{2}}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrSizeWrap,Py_Noneret,def{90},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_charPtrSizeWrap,str,def{82},use{86,90,91},dvars{Py_Noneret},pointers{},cfuncs{VIR_FREE{1},PyString_FromStringAndSize{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongWrap,retret,def{77},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongWrap,ret,def{76},use{78},dvars{},pointers{info},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulonglongWrap,val,def{74},use{77},dvars{retret},pointers{},cfuncs{PyLong_FromUnsignedLongLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongWrap,retret,def{69},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongWrap,ret,def{68},use{70},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_longlongWrap,val,def{66},use{69},dvars{retret},pointers{},cfuncs{PyLong_FromUnsignedLongLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainSnapshotPtrWrap,ret,def{457},use{465},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainSnapshotPtrWrap,Py_Noneret,def{464},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_virDomainSnapshotPtrWrap,node,def{455},use{26,33,35,459,464},dvars{Py_Noneret},pointers{},cfuncs{PyCObject_FromVoidPtrAndDesc{1},PyCapsule_New{1},libvirt_buildPyObject{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongUnwrap,long_val,def{199,206},use{207,210,211},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongUnwrap,val,def{197,211},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongUnwrap,obj,def{197},use{201,206},dvars{long_val},pointers{},cfuncs{PyInt_AsLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_intWrap,retret,def{45},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_intWrap,ret,def{44},use{46},dvars{},pointers{local,disks,info,remote},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_intWrap,val,def{42},use{45},dvars{retret},pointers{},cfuncs{PyInt_FromLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_intUnwrap,long_val,def{125,136},use{137,141,142,149},dvars{val},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_intUnwrap,val,def{123,142,149},use{},dvars{},pointers{temp,val,i},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_intUnwrap,obj,def{123},use{127,136},dvars{long_val},pointers{},cfuncs{PyInt_AsLong{1}}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongWrap,retret,def{61},use{},dvars{},pointers{},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongWrap,ret,def{60},use{62},dvars{},pointers{info},cfuncs{}
libvirt-1.1.0/python/typewrappers.c,libvirt_ulongWrap,val,def{58},use{61},dvars{retret},pointers{},cfuncs{PyLong_FromLong{1}}
